spring.application.name=PlacementAnalyzer

spring.datasource.url=jdbc:mysql://mysql-1727800b-khanishkareddykondreddy34-6774.h.aivencloud.com:17797/defaultdb?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.7-flash